---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-dr-system
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ramen-operator-group
  namespace: openshift-dr-system
