# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- ../bases/ramen_dr_cluster.clusterserviceversion.yaml
- ../../default
- ../../samples
- ../../../scorecard
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: '[{"op": "add", "path": "/metadata/annotations/olm.skipRange", "value": ""}]'
  target:
    kind: ClusterServiceVersion
    name: ramen-dr-cluster-operator.v0.0.0
- patch: '[{"op": "replace", "path": "/spec/replaces", "value": ""}]'
  target:
    kind: ClusterServiceVersion
    name: ramen-dr-cluster-operator.v0.0.0
