---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ramen-dr-cluster-subscription
  namespace: openshift-dr-system
spec:
  channel: "alpha"
  installPlanApproval: Automatic
  name: ramen-dr-cluster-operator
  source: ramen-catalog
  sourceNamespace: openshift-dr-system
  startingCSV: ramen-dr-cluster-operator.v0.0.1
